version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: investor_postgres
    environment:
      POSTGRES_DB: venture_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data
      - ./sql:/docker-entrypoint-initdb.d

  mongo:
    image: mongo:6
    container_name: mongo_db
    ports:
      - "27017:27017"
    volumes:
      - ./mongodata:/data/db

  neo4j:
    image: neo4j:5
    container_name: neo4j_db
    environment:
      - NEO4J_AUTH=none
    ports:
      - "7474:7474"   # Browser UI
      - "7687:7687"   # Bolt protocol
    volumes:
      - ./neo4jdata:/data
